name: build

on: ["push", "pull_request"]

jobs: 

 test_development:
  # Testing in development environment: functionality and code-format
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}

    - name: Setup conda and environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          channels: conda-forge,defaults
          mamba-version: "*"
          channel-priority: true
          activate-environment: coco-dev
          environment-file: environment.yml
          use-only-tar-bz2: true   # required for caching

    - name: List environment
      run: |
        mamba info
        mamba list

    - name: Run tests
      run: |
         isort --project country_converter --profile black --check-only .
         coverage run --source=country_converter -m pytest --black -vv

    - name: Coveralls analysis
      run: COVERALLS_REPO_TOKEN=S31b5QjHBJmjGAj5b0IHTdyaHxRkNfO5E coveralls


 test_production:
   # Testing if the package runs on different systems/python versions
    needs: test_development
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # removed -l as this breaks in mac-os
        shell: bash {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.8]

    steps:
       - name: Check out repository code
         uses: actions/checkout@v2

       - name: Setup Python
         uses: actions/setup-python@v2
         with:
            python-version: ${{matrix.python-version}}

       - name: Run tests
         run: |
            pip install . -U
            pip install pytest
            python setup.py sdist
            pytest -vv
            
 armv64_job:
    name: Build and Test for arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
           docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
             arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install git python3 python3-pip && \
              python3 -m pip install --upgrade pip && \
              pip install . -U && \
              pip install pytest && \
              python3 setup.py sdist && \
              pytest -vv && \
              deactivate'
